# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jacek Kowalczyk @ IT World
email: jack82@bsdmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my next web place next to other like my wordpress blog https://jacekkowalczyk.wordpress.com/
  I am Software and Test Engineer interested in OpenSource especially #BSD, #Linux, #kalilinux, #Debian, #FreeBSD, #opensource
 

# URL of your avatar or profile pic (you could use your GitHub profile pic)
#avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
avatar: /assets/images/avatar-logo.jpg

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jacekkowalczyk82.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jacekkowalczy10
#mastodon: https://mastodon.technology/@kowalczy
mastodon: 
  - username: kowalczy
    instance: mastodon.technology

googleplus_username: +JacekKowalczyk
github_username:  jacekkowalczyk82
linkedin_username: jacek-kowalczyk-4800644

# Build settings
exclude: [jekyll-minima-theme.md, do_not_render_content]
markdown: kramdown

theme: minima
#theme: minima
#theme: jekyll-theme-hacker
#theme: jekyll-theme-midnight
#theme: jekyll-theme-architect
#theme: jekyll-theme-slate
#theme: jekyll-theme-jacek-blog

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
